package channel

import (
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"shachiku/core/config"
)

func downloadFileToTmp(url, filename string) (string, error) {
	tmpDir := filepath.Join(config.GetDataDir(), "tmp")
	if err := os.MkdirAll(tmpDir, 0755); err != nil {
		return "", err
	}

	// Make sure filename is not empty and strip path components just in case
	filename = filepath.Base(filename)
	if filename == "." || filename == "" {
		filename = "downloaded_file"
	}

	ext := filepath.Ext(filename)
	base := filename[:len(filename)-len(ext)]
	newFileName := fmt.Sprintf("%s_%d%s", base, time.Now().Unix(), ext)
	outPath := filepath.Join(tmpDir, newFileName)

	resp, err := http.Get(url)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("bad status: %s", resp.Status)
	}

	out, err := os.Create(outPath)
	if err != nil {
		return "", err
	}
	defer out.Close()

	if _, err := io.Copy(out, resp.Body); err != nil {
		return "", err
	}

	return outPath, nil
}

// MarkdownToTelegramHTML selectively converts standard Markdown generated by LLMs
// to Telegram-supported HTML, which avoids the strict escaping problems of MarkdownV2.
func MarkdownToTelegramHTML(md string) string {
	type codeBlock struct {
		placeholder string
		content     string
	}
	var blocks []codeBlock

	// 1. Extract block code (```...```)
	blockRegex := regexp.MustCompile("(?s)```(.*?)```")
	md = blockRegex.ReplaceAllStringFunc(md, func(match string) string {
		sub := match[3 : len(match)-3]
		placeholder := fmt.Sprintf("%%CODEBLOCK_%d%%", len(blocks))
		escapedCode := strings.ReplaceAll(sub, "&", "&amp;")
		escapedCode = strings.ReplaceAll(escapedCode, "<", "&lt;")
		escapedCode = strings.ReplaceAll(escapedCode, ">", "&gt;")

		lines := strings.SplitN(escapedCode, "\n", 2)
		var htmlContent string
		if len(lines) == 2 && !strings.ContainsAny(lines[0], " \t") && len(lines[0]) > 0 {
			htmlContent = fmt.Sprintf("<pre><code class=\"language-%s\">%s</code></pre>", lines[0], lines[1])
		} else {
			htmlContent = fmt.Sprintf("<pre><code>%s</code></pre>", escapedCode)
		}

		blocks = append(blocks, codeBlock{placeholder, htmlContent})
		return placeholder
	})

	// 2. Extract inline code (`...`)
	inlineRegex := regexp.MustCompile("(?s)`(.*?)`")
	md = inlineRegex.ReplaceAllStringFunc(md, func(match string) string {
		sub := match[1 : len(match)-1]
		placeholder := fmt.Sprintf("%%INLINEBLOCK_%d%%", len(blocks))
		escapedCode := strings.ReplaceAll(sub, "&", "&amp;")
		escapedCode = strings.ReplaceAll(escapedCode, "<", "&lt;")
		escapedCode = strings.ReplaceAll(escapedCode, ">", "&gt;")
		htmlContent := fmt.Sprintf("<code>%s</code>", escapedCode)
		blocks = append(blocks, codeBlock{placeholder, htmlContent})
		return placeholder
	})

	// Now we can safely escape HTML characters in the rest of the text
	md = strings.ReplaceAll(md, "&", "&amp;")
	md = strings.ReplaceAll(md, "<", "&lt;")
	md = strings.ReplaceAll(md, ">", "&gt;")

	// 3. Bold (**...**)
	boldRegex := regexp.MustCompile(`\*\*(.*?)\*\*`)
	md = boldRegex.ReplaceAllString(md, "<b>$1</b>")

	// 4. Italic (*...* and _..._)
	italicRegex1 := regexp.MustCompile(`\*([^\*]+)\*`)
	md = italicRegex1.ReplaceAllString(md, "<i>$1</i>")

	italicRegex2 := regexp.MustCompile(`\b_([^_]+)_\b`)
	md = italicRegex2.ReplaceAllString(md, "<i>$1</i>")

	// 5. Strikethrough (~~...~~)
	strikeRegex := regexp.MustCompile(`~~(.*?)~~`)
	md = strikeRegex.ReplaceAllString(md, "<s>$1</s>")

	// 6. Links [text](URL)
	linkRegex := regexp.MustCompile(`\[([^\]]+)\]\(([^)]+)\)`)
	md = linkRegex.ReplaceAllString(md, "<a href=\"$2\">$1</a>")

	// Restore code blocks
	for _, block := range blocks {
		md = strings.Replace(md, block.placeholder, block.content, 1)
	}

	return md
}
